name: Generate and save libraries

on:
  push:
    branches:
      - master
jobs:
  build_libs:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        language: [php, python, go]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Generate ${{ matrix.language }}
        run: npm run api:build:client ${{ matrix.language }}
      - name: Set REPO_USER env
        run: echo "REPO_USER=$(echo $GITHUB_REPOSITORY | cut -d / -f1)" >> $GITHUB_ENV
      - name: Set REPO_NAME env
        run: echo "REPO_NAME=mainnet-${{ matrix.language }}-generated" >> $GITHUB_ENV
      - name: Commit to ${{ matrix.language }} repository
        uses: drud/action-cross-commit@master
        with:
          source-folder: generated/client/${{ matrix.language }}
          destination-repository: https://${{ env.REPO_USER }}:${{ secrets.COMMIT_USER_TOKEN }}@github.com/${{ env.REPO_USER }}/${{ env.REPO_NAME }}
          destination-folder: .
          destination-branch: master
          git-user: "Auto-Generated"
          git-user-email: hello@mainnet.cash
          git-commit-message: "Generated"
          excludes: .git:path/deeper/in/the/repo
